Tienda/modulos/puestos/views.py
from flask import Blueprint, render_template, redirect, request
from Tienda.modulos.puestos.model.puestos import Puesto
from Tienda.modulos.empleados.model.empleados import Empleado
from sqlalchemy import not_, or_
from Tienda.modulos import db

bp_puestos = Blueprint("puestos", __name__)

@bp_puestos.route('/puestos/')
def puestos():
    cdx={
        "puestos":Puesto.query.all()
    }
    return render_template("puestos/puestos.html",cdx=cdx)

@bp_puestos.route('/puestos/alta/', methods=['GET', 'POST'])
def alta():
    if request.method == 'GET':
        cdx={
            'tipo':'alta',
            'empleados':Empleado.query.all()
        }
        return render_template("puestos/ABC_puestos.html",cdx=cdx)
    elif request.method == 'POST':
        nombre = request.form.get("nombre")
        empleado = int(request.form.get("empleado"))
        empleado = Empleado.query.get({'id': empleado})
        puesto = Puesto(
            puesto=nombre,
            empleado=empleado
        )
        db.session.add(puesto)
        db.session.commit()
        return redirect('/puestos/')


@bp_puestos.route('/puestos/borrar/<int:id>/', methods=['GET', 'POST'])
def baja(id):
    if request.method == 'GET':
        cdx={
            'tipo':'baja',
            'puesto':Puesto.query.get({'id': id}),
            'empleados': Empleado.query.all()
        }
        return render_template("puestos/ABC_puestos.html",cdx=cdx)
    elif request.method == 'POST':
        #del(EMPLEADOS[id])
        e = Puesto.query.get({'id': id})
        if e:
            db.session.delete(e)
            db.session.commit()
        return redirect("/puestos/")
    else:
        return "Error"

@bp_puestos.route('/puestos/cambio/<int:id>/', methods=['GET', 'POST'])
def cambio(id):
    if request.method == 'GET':
        cdx={
            'tipo':'cambio',
             'puesto':Puesto.query.get({'id': id}),
            'empleados': Empleado.query.all()
        }
        return render_template("puestos/ABC_puestos.html",cdx=cdx)
    elif request.method == 'POST':
        nombre = request.form.get("nombre")
        empleado = int(request.form.get("empleado"))
        empleado = Empleado.query.get({'id': empleado})
        e = Puesto.query.get({'id': id})
        if e:
            e.puesto=nombre
            e.empleado=empleado
            db.session.add(e)
            db.session.commit()
        return redirect('/puestos/')

Tienda/modulos/templates/puestos/ABC_puestos.html
{% extends  "home/index.html"%}
{% block encabezado %}
    {% if cdx.tipo == 'alta' %}
    <h1>Crear puesto nuevo</h1>
    {% elif cdx.tipo == 'baja' %}
    <h1>Borrar puesto</h1>
    {% elif cdx.tipo == 'cambio' %}
    <h1>Editar puesto</h1>
    {% else %}
    <h1>Error</h1>
    {% endif %}
{% endblock %}

{% block cuerpo %}
<form class="w3-container w3-card-4
    {% if cdx.tipo == 'alta' %}
    w3-light-grey
    {% elif cdx.tipo == 'baja' %}
    w3-pale-red
    {% elif cdx.tipo == 'cambio' %}
    w3-pale-green
    {% else %}
    w3-black
    {% endif %}" method="post">
<div class="w3-row-padding">
  <div class="w3-third">
      <label for="nombre">Puesto:</label>
    <input name="nombre"
           id="nombre"
           class="w3-input w3-border"
           type="text"
           {% if cdx.tipo != 'alta' %}
           value="{{ cdx.puesto.puesto }}"
           {% endif %}
           placeholder="Puesto">
  </div>
  <div class="w3-third">
      <label for="empleado">Empleado:</label>
    <select name="empleado" id="empleado" class="w3-select w3-border">
    <option value=0 disabled selected>Selecciona un empleado</option>
    {% for e in cdx.empleados %}
        <option value={{ e.id }} {% if cdx.tipo != 'alta' and cdx.puesto.empleado.id == e.id %}selected{% endif %} >{{ e.nombre }} {{ e.apellido }}</option>
    {% endfor %}
    </select>
  </div>
</div>


<button type="submit" class="w3-button w3-teal w3-section w3-ripple w3-padding">
    {% if cdx.tipo == 'alta' %}
    Crear
    {% elif cdx.tipo == 'baja' %}
    Borrar
    {% elif cdx.tipo == 'cambio' %}
    Guardar
    {% endif %}
</button>
</form>
{% endblock %}

Tienda/modulos/templates/puestos/puestos.html
{% extends  "home/index.html"%}
{% block encabezado %}
    <h1>Puestos <a href="{{ url_for('puestos.alta')}}"><button class="w3-button w3-circle">+</button></a></h1>
{% endblock %}
{% block cuerpo %},e
    <div class="w3-responsive">
    <table class="w3-table-all w3-hoverable">
    <thead>
      <tr class="w3-light-grey">
        <th class="w3-center">Borrar</th>
        <th class="w3-center">Editar</th>
          <th>Puesto</th>
        <th>Nombre</th>
        <th>Apellido</th>
        <th class="w3-center">Sexo</th>
        <th class="w3-right">Edad</th>
        <th>Salario</th>
      </tr>
    </thead>
        {% for puesto in cdx.puestos %}
    <tr>
        <td class="w3-center"><a href="{{ url_for('puestos.baja',id=puesto.id)}}"><img src="https://img.icons8.com/3d-plastilina/32/null/delete-sign--v2.png"></a></td>
        <td class="w3-center"><a href="{{ url_for('puestos.cambio',id=puesto.id)}}"><img src="https://img.icons8.com/fluency/48/null/pencil-tip.png"></a></td>
        <td>{{ puesto.puesto | default("Suplente",True)}}</td>
        <td>{{ puesto.empleado.nombre }}</td>
      <td>{{ puesto.empleado.apellido }}</td>
      <td class="w3-center">{{ puesto.empleado.sexo | replace("H","Hombre") | replace("M","Mujer") | replace("N","Neutral")}}</td>
        <td class="w3-right">{{ puesto.empleado.edad }}</td>
        <td>{{ puesto.empleado.salario | formato_moneda}}</td>
    </tr>
        {% endfor %}
  </table>

    </div>
{% endblock %}