Tienda/modulos/empleados/views.py
from flask import Blueprint, render_template, redirect, request
from Tienda.modulos.empleados.model.empleadosOld import EMPLEADOS
from Tienda.modulos.empleados.model.empleados import Empleado
from sqlalchemy import not_, or_
from Tienda.modulos import db

bp_empleados = Blueprint("empleados", __name__)

@bp_empleados.route('/empleados/')
def empleados():
    #for a,b in EMPLEADOS.items():
    #    print(f"{a} : {b}")
    cdx={
        "empleados":Empleado.query.all()
    }
    return render_template("empleados/empleados.html",cdx=cdx)

@bp_empleados.route('/empleados/pruebas')
def pruebas():
    # consulta que solo regresa 2 registros
    Empleado.query.limit(2).all()
    # consulta que regresa los registros ordenados por salario
    Empleado.query.order_by(Empleado.salario.desc()).all()
    #consulta que no regresa una lista, solo 1 empleado
    Empleado.query.get({'id': 2})
    #consulta por nombre, no toma en ceunta las mayusculas
    Empleado.query.filter_by(nombre='Luis').all()
    #consulta los registros menor o igual que jose
    Empleado.query.filter(Empleado.nombre <= 'Jose').all()
    print(Empleado.query.filter_by(nombre='Luis', id=3).all())
    print(Empleado.query.filter(Empleado.nombre.like('%s%')).all())
    print(Empleado.query.filter(not_(Empleado.nombre == 'Jose')).all())
    print(Empleado.query.filter(or_(Empleado.nombre == 'Jose', Empleado.edad > 30)).all())
    # Crear registro
    e = Empleado(nombre='Pedro', apellido='Peralta', sexo='H', edad=32,
                 salario=42160, comentarios='', puesto='patron')
    db.session.add(e)
    db.session.commit()
    # Eliminar registro
    e = Empleado.query.filter_by(nombre='Pedro').first()
    if e:
        db.session.delete(e)
        db.session.commit()
    cdx={
        "empleados":Empleado.query.all()
    }
    return render_template("empleados/empleados.html",cdx=cdx)

@bp_empleados.route('/empleados/comentarios/<int:id>/')
def comentarios(id):
    #empleado = f"id={id}, tipo={type(id)}."
    empleado = Empleado.query.get({'id': id})# EMPLEADOS[id]
    return empleado.comentarios

@bp_empleados.route('/empleados/borrar/<int:id>/', methods=['GET', 'POST'])
def baja(id):
    if request.method == 'GET':
        cdx={
            'tipo':'baja',
            'empleado':Empleado.query.get({'id': id}) #EMPLEADOS[id]
        }
        return render_template("empleados/ABC_empleados.html",cdx=cdx)
    elif request.method == 'POST':
        #del(EMPLEADOS[id])
        e = Empleado.query.get({'id': id})
        if e:
            db.session.delete(e)
            db.session.commit()
        return redirect("/empleados/")
    else:
        return "Error"

@bp_empleados.route('/empleados/cambio/<int:id>/', methods=['GET', 'POST'])
def cambio(id):
    if request.method == 'GET':
        cdx={
            'tipo':'cambio',
            'empleado':Empleado.query.get({'id': id})#EMPLEADOS[id]
        }
        return render_template("empleados/ABC_empleados.html",cdx=cdx)
    elif request.method == 'POST':
        e = Empleado.query.get({'id': id})
        if e:
            e.nombre= request.form.get("nombre")
            e.apellido = request.form.get("apellido")
            sexo = request.form.get("sexo")
            if sexo == '1':
                e.sexo = 'H'
            elif sexo == '2':
                e.sexo = 'M'
            else:
                e.sexo = 'N'
            e.puesto = request.form.get("puesto")
            e.edad = request.form.get("edad")
            salario = request.form.get("salario")
            salario = salario.replace('$','')
            salario = salario.replace(',', '')
            e.salario = float(salario)
            e.comentario = request.form.get("comentario")
            db.session.add(e)
            db.session.commit()


        # EMPLEADOS[id]['nombre'] = request.form.get("nombre")
        # EMPLEADOS[id]['apellido'] = request.form.get("apellido")
        # sexo = request.form.get("sexo")
        # if sexo == '1':
        #     EMPLEADOS[id]['sexo'] = 'H'
        # elif sexo == '2':
        #     EMPLEADOS[id]['sexo'] = 'M'
        # else:
        #     EMPLEADOS[id]['sexo'] = 'N'
        # EMPLEADOS[id]['puesto'] = request.form.get("puesto")
        # salario = request.form.get("salario")
        # salario = salario.replace('$','')
        # salario = salario.replace(',', '')
        # EMPLEADOS[id]['salario'] = float(salario)
        # EMPLEADOS[id]['comentario'] = request.form.get("comentario")


        return redirect("/empleados/")
    else:
        return "Error"

@bp_empleados.route('/empleados/nuevo', methods=['GET', 'POST'])
def alta():
    if request.method == 'GET':
        cdx = {
            'tipo': 'alta',
            'empleado': None
        }
        return render_template("empleados/ABC_empleados.html",cdx=cdx)
    elif request.method == 'POST':
        nombre = request.form.get("nombre")
        apellido = request.form.get("apellido")
        sexo = request.form.get("sexo")
        if sexo == '1':
            sexo = 'H'
        elif sexo == '2':
            sexo = 'M'
        else:
            sexo = 'N'
        puesto = request.form.get("puesto")
        edad = request.form.get("edad")
        salario = request.form.get("salario")
        salario = salario.replace('$', '')
        salario = salario.replace(',', '')
        salario = float(salario)
        comentario = request.form.get("comentario")
        e = Empleado(
            nombre=nombre,
            apellido=apellido,
            sexo=sexo,
            edad=edad,
            puesto=puesto,
            salario=salario,
            comentarios=comentario
        )
        db.session.add(e)
        db.session.commit()
        return redirect("/empleados/")
    else:
        return "ERROR"

@bp_empleados.app_template_filter('formato_moneda')
def formato_moneda(numero:float):
    if(numero):
        return f"${numero:0,.2f}"
    return f"${0:0,.2f}"

Tienda/modulos/templates/empleados/ABC_empleados.html
{% extends  "home/index.html"%}
{% block encabezado %}
    {% if cdx.tipo == 'alta' %}
    <h1>Crear empleado nuevo</h1>
    {% elif cdx.tipo == 'baja' %}
    <h1>Borrar empleado</h1>
    {% elif cdx.tipo == 'cambio' %}
    <h1>Editar empleado</h1>
    {% else %}
    <h1>Error</h1>
    {% endif %}
{% endblock %}

{% block cuerpo %}
<form class="w3-container w3-card-4
    {% if cdx.tipo == 'alta' %}
    w3-light-grey
    {% elif cdx.tipo == 'baja' %}
    w3-pale-red
    {% elif cdx.tipo == 'cambio' %}
    w3-pale-green
    {% else %}
    w3-black
    {% endif %}" method="post">
<div class="w3-row-padding">
  <div class="w3-third">
      <label for="nombre">Nombre:</label>
    <input name="nombre"
           id="nombre"
           class="w3-input w3-border"
           type="text"
           {% if cdx.tipo != 'alta' %}
           value="{{ cdx.empleado.nombre }}"
           {% endif %}
           placeholder="Nombre">
  </div>
  <div class="w3-third">
      <label for="apellido">Apellido:</label>
    <input name="apellido" id="apellido" class="w3-input w3-border" type="text" placeholder="Apellido"
    {% if cdx.tipo != 'alta' %}
        value="{{ cdx.empleado.apellido }}"
            {% endif %}
    >
  </div>
  <div class="w3-third">
      <label for="sexo">Sexo:</label>
      <p>
  <input class="w3-radio" type="radio" name="sexo" id="id_hombre" value=1
  {% if cdx.empleado.sexo == 'H' %}
          checked
  {% endif %}
  >
  <label for="id_hombre">Hombre</label>

  <input class="w3-radio" type="radio" name="sexo" id="id_mujer" value=2
    {% if cdx.empleado.sexo == 'M' %}
          checked
  {% endif %}>
  <label for="id_mujer">Mujer</label>

  <input class="w3-radio" type="radio" name="sexo" id="id_ningunsexo" value=3
    {% if cdx.empleado.sexo == 'N' %}
          checked
  {% endif %}
  >
  <label for="id_ningunsexo">Prefiero no decir..</label>
      </p>
  </div>
</div>
     <div class="w3-row">
  <div class="w3-half w3-container">
    <div class="w3-row">
  <div class="w3-third">
     <label for="edad">Edad:</label>
    <input name="edad" id="edad" class="w3-input w3-border" type="number"
    {% if cdx.tipo != 'alta' %}
        value="{{ cdx.empleado.edad }}"
    {% endif %}
    >

  </div>
        <div class="w3-third">
             <label for="puesto">Puesto:</label>
    <input name="puesto" id="puesto" class="w3-input w3-border" type="text" placeholder="puesto"
    {% if cdx.tipo != 'alta' %}
           value="{{ cdx.empleado.puesto }}"
           {% endif %}
    >

  </div>
        <div class="w3-third">
          <label for="salario">Salario:</label>
    <input name="salario" id="salario" class="w3-input w3-border" type="text"
    {% if cdx.tipo != 'alta' %}
           value="{{ cdx.empleado.salario | formato_moneda }}"
           {% endif %}
    >

  </div>
    </div>
  </div>
  <div class="w3-half w3-container">
    <label for="comentario">Comentario:</label>
    <input name="comentario" id="comentario" class="w3-input w3-border" type="text" placeholder="comentario"
    {% if cdx.tipo != 'alta' %}
           value="{{ cdx.empleado.comentario }}"
           {% endif %}>

  </div>
</div>
<button type="submit" class="w3-button w3-teal w3-section w3-ripple w3-padding">
    {% if cdx.tipo == 'alta' %}
    Crear
    {% elif cdx.tipo == 'baja' %}
    Borrar
    {% elif cdx.tipo == 'cambio' %}
    Guardar
    {% endif %}
</button>
</form>
{% endblock %}

Tienda/modulos/templates/empleados/empleados.html
{% extends  "home/index.html"%}
{% block encabezado %}
    <h1>Empleados <a href="{{ url_for('empleados.alta')}}"><button class="w3-button w3-circle">+</button></a></h1>
{% endblock %}
{% block cuerpo %}
    <div class="w3-responsive">
    <table class="w3-table-all w3-hoverable">
    <thead>
      <tr class="w3-light-grey">
          <th class="w3-center">Borrar</th>
          <th class="w3-center">Editar</th>
        <th>Nombre</th>
        <th>Apellido</th>
        <th class="w3-center">Sexo</th>
          <th class="w3-right">Edad</th>
          <th>Puesto</th>
          <th>Salario</th>
          <th>Comentarios</th>
      </tr>
    </thead>
        {% for empleado in cdx.empleados %}
    <tr>
        <td class="w3-center"><a href="{{ url_for('empleados.baja',id=empleado.id)}}"><img src="https://img.icons8.com/3d-plastilina/32/null/delete-sign--v2.png"></a></td>
        <td class="w3-center"><a href="{{ url_for('empleados.cambio',id=empleado.id)}}"><img src="https://img.icons8.com/fluency/48/null/pencil-tip.png"></a></td>
        <td>{{ empleado.nombre }}</td>
      <td>{{ empleado.apellido }}</td>
      <td class="w3-center">{{ empleado.sexo | replace("H","Hombre") | replace("M","Mujer") | replace("N","Neutral")}}</td>
        <td class="w3-right">{{ empleado.edad }}</td>
        <td>{{ empleado.puesto | default("Suplente",True)}}</td>
        <td>{{ empleado.salario | formato_moneda}}</td>
    <td><a href="{{ url_for('empleados.comentarios',id=empleado.id)}}">ver comentarios</a></td>
    </tr>
        {% endfor %}
  </table>

    </div>
{% endblock %}